M48
; DRILL file {KiCad 9.0.6} date 2026-04-28T16:02:02+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-28T16:02:02+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.300
%
G90
G05
T2
X121.4Y-87.2
X133.4Y-87.2
X136.7Y-87.2
X148.7Y-87.2
X152.0Y-87.2
X164.0Y-87.2
T1
X162.9Y-54.25G85X162.9Y-53.45
G05
M30
